<?php
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder' => 'Nome da categoria'
]);
$form->get('submit')->setAttributes(['class'=>'btn btn-success btn-cons']);

$form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <div class="grid simple form-grid">
            <div class="grid-title no-border">
                <h4>Categoria</h4>
            </div>
            <div class="grid-body no-border">
                <?= $this->form()->openTag($form); ?>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                    </div>
                    <div class="form-actions">
                        <div class="pull-right">
                            <?= $this->formElement($form->get('submit')); ?>
                            <button class="btn btn-white btn-cons" type="button">Cancel</button>
                        </div>
                    </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>