
<div class="row">
    <div class="col-md-12">
        <div class="grid simple ">
            <div class="grid-title no-border">
                <h4>Categorias</h4>
                <div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                    <a href="#grid-config" data-toggle="modal" class="config"></a>
                    <a href="javascript:;" class="reload"></a>
                    <a href="javascript:;" class="remove"></a>
                </div>
            </div>
            <div class="grid-body no-border">
                <table class="table table-striped table-flip-scroll cf">
                    <thead class="cf">
                    <tr>
                        <th>Nome</th>
                        <th width="50px"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($bookCategories as $category):?>
                    <tr>
                        <td><?= $category->getName() ?></td>
                        <td>
                            <span class="label label-important">DELETAR</span>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>