<div class="row">
    <div class="col-md-12">
        <div class="grid simple ">
            <div class="grid-title no-border">
                <h4>Livros</h4>
                <div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                    <a href="#grid-config" data-toggle="modal" class="config"></a>
                    <a href="javascript:;" class="reload"></a>
                    <a href="javascript:;" class="remove"></a>
                </div>
            </div>
            <div class="grid-body no-border">
                <table class="table table-striped table-flip-scroll cf">
                    <thead class="cf">
                    <tr>
                        <th>Nome</th>
                        <th>Categoria</th>
                        <th width="50px"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($books as $book): ?>
                        <tr>
                            <td>
                                <a href="<?= $this->url('book_category', ['action' => 'edit', 'id' => $book->getId()]) ?>">
                                    <?= $book->getName() ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?= $this->url('book_category', ['action' => 'edit', 'id' => $book->getId()]) ?>">
                                    <?= $book->getBookCategory()->getName() ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?= $this->url('book_category', ['action' => 'delete', 'id' => $book->getId()]); ?>" class="label label-important">DELETAR</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>