<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<body id="auth_wrapper">
<div id="login_wrapper">

    <div id="login_content">
        <div class="logo">
            <img src="assets/img/logo/ml-logo.png" alt="logo" class="logo-img">
        </div>
        <h1 class="login-title">
            Sign In to your account
        </h1>
        <div class="login-body">
            <form>
                <div class="form-group label-floating is-empty">
                    <label class="control-label">Email</label>
                    <input type="email" class="form-control">
                </div>
                <div class="form-group label-floating is-empty">
                    <label class="control-label">Password</label>
                    <input type="password" class="form-control">
                </div>
                <a href="javascript:void(0)" class="forgot-pass pull-right">Forgot Password?</a>
                <div class="checkbox inline-block">
                    <label>
                        <input type="checkbox" class="checkbox-inline" value="">
                        Remember Me
                    </label>
                </div>
                <a href="index.html" class="btn btn-info btn-block m-t-40">Sign In</a>
                <div class="login-options">
                    <span>OR</span>
                    <hr/>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <button class="btn btn-facebook btn-block"><i class="zmdi zmdi-facebook"></i> Sign In with Facebook</button>
                    </div>
                    <div class="col-xs-12">
                        <button class="btn btn-google btn-block"><i class="zmdi zmdi-google-plus"></i> Sign In with Google</button>
                    </div>
                    <div class="col-xs-12">
                        <button class="btn btn-twitter btn-block"><i class="zmdi zmdi-twitter"></i> Sign In with Twitter</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="login-footer p-15">
            <p>
                Don't have an account? <a href="javascript:void(0)" data-toggle="register">Create an account</a>
            </p>
        </div>
        <div id="register_wrapper">
            <ul class="card-actions icons right-top">
                <li>
                    <a href="javascript:void(0)" data-toggle="register">
                        <i class="zmdi zmdi-close"></i>
                    </a>
                </li>
            </ul>
            <div class="logo">
                <img src="assets/img/logo/ml-logo.png" alt="logo" class="logo-img">
            </div>
            <h1 class="login-title">
                Create an account
            </h1>
            <div class="login-body">
                <div class="col-xs-12">
                    <button class="btn btn-facebook btn-block"><i class="zmdi zmdi-facebook"></i> Sign Up with Facebook</button>
                </div>
                <div class="col-xs-12">
                    <button class="btn btn-google btn-block"><i class="zmdi zmdi-google-plus"></i> Sign Up with Google</button>
                </div>
                <div class="col-xs-12">
                    <button class="btn btn-twitter btn-block"><i class="zmdi zmdi-twitter"></i> Sign Up with Twitter</button>
                </div>

                <form class="clear-both">
                    <h2 class="text-center p-t-20">
                        Or sign up below
                    </h2>
                    <div class="form-group label-floating is-empty">
                        <label class="control-label">Name</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group label-floating is-empty">
                        <label class="control-label">Email</label>
                        <input type="email" class="form-control">
                    </div>
                    <div class="form-group label-floating is-empty">
                        <label class="control-label">Password</label>
                        <input type="password" class="form-control">
                    </div>
                    <div class="form-group label-floating is-empty">
                        <label class="control-label">Confirm Password</label>
                        <input type="password" class="form-control">
                    </div>
                    <div class="checkbox inline-block">
                        <label>
                            <input type="checkbox" class="checkbox-inline" value="">
                            I agree to the <a href="javascript:void(0)">terms of services</a>
                        </label>
                    </div>
                    <a href="javascript:void(0)" class="btn btn-info btn-block m-t-40">Create my account</a>
                </form>
            </div>
            <div class="login-footer p-15">
                <p>
                    Already have an account? <a href="javascript:void(0)" data-toggle="register">Sign In</a>
                </p>
            </div>
        </div>
    </div>
</div>
<script src="assets/js/vendor.bundle.js"></script>
<script src="assets/js/app.bundle.js"></script>
</body>
</body>
</html>
