<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/vendor.bundle.css'))
        ->prependStylesheet($this->basePath('css/app.bundle.css'))
        ->prependStylesheet($this->basePath('css/theme-a.css'));
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/vendor.bundle.'))
        ->prependFile($this->basePath('js/app.bundle.js'));
    ?>
</head>
<body>
<body id="auth_wrapper">
<div id="login_wrapper">

    <div id="login_content">
        <h1 class="login-title">
            Entre com o email e a senha
        </h1>
        <div class="login-body">
            <form>
                <div class="form-group label-floating is-empty">
                    <label class="control-label">Email</label>
                    <input type="email" class="form-control">
                </div>
                <div class="form-group label-floating is-empty">
                    <label class="control-label">Password</label>
                    <input type="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-info btn-block m-t-40">Sign In</button>
            </form>
        </div>
    </div>
</div>
</body>
</body>
</html>
